// <auto-generated />
namespace MonthlyBudget.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialtablescreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialtablescreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201612081846483_initial tables created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
